CREATE TABLE registros (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    "Data" TEXT,
    "Integrado" TEXT,
    "Alojamento" TEXT,
    "Idade" NUMERIC,
    "Animais Alojados" NUMERIC,
    "Animais Mortos" NUMERIC,
    "Vol. Cargas (kg)" NUMERIC,
    "Recomendação" TEXT,
    "Consumo acumulado" NUMERIC,
    "Comedouro" TEXT,
    "Colaborador" TEXT,
    "Meta Aloj" NUMERIC,
    "Cons. Aloj" NUMERIC,
    "Meta Cresc 1" NUMERIC,
    "Cons. Cresc 1" NUMERIC,
    "Meta Cresc 2" NUMERIC,
    "Cons. Cresc 2" NUMERIC,
    "Meta Cresc 3" NUMERIC,
    "Cons. Cresc 3" NUMERIC,
    "Meta Term 1" NUMERIC,
    "Cons. Term 1" NUMERIC,
    "Meta Term 2" NUMERIC,
    "Cons. Term 2" NUMERIC,
    "Meta Acum." NUMERIC,
    "Peso aloj" NUMERIC,
    "Pontuação Sanitária" NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
